export default [
    {
        title:"Techtravel in Tokyo",
        location: "Japan, Tokyo",
        startDate: "04. August",
        endDate:"12. August",
        description: "There were alot of amazing Tech gadgets, that i found interesting",
        imageUrl:"https://media.cntraveler.com/photos/63482b255e7943ad4006df0b/16:9/w_2560%2Cc_limit/tokyoGettyImages-1031467664.jpeg",
    },

    {
        title:"History night Berlin",
        location: "Berlin, Germany",
        startDate: "09. February",
        endDate:"31. Ferbruary",
        description: "Berlin is full of History, starting with the Berlin-Gate and continueing with the fall of the Wall",
        imageUrl:"https://a.cdn-hotels.com/gdcs/production154/d1887/471414c9-f456-4041-83f5-d7b61063d287.jpg?impolicy=fcrop&w=800&h=533&q=medium",
    },

    {
        title:"Paris was not that romantic",
        location: "France, Paris",
        startDate: "26. March",
        endDate:"11. April",
        description: "Movies often say, that Paris is the most romantic City, but we have differnt thoughts",
        imageUrl:"https://www.americanexpress.com/de-de/amexcited/media/cache/default/cms/2022/03/paris-sehenswuerdigkeiten-titelbild.jpg",
    },

    {
        title:"Sunny adventures in Florida",
        location: "US, Florida",
        startDate: "02. May",
        endDate:"12. May",
        description: "Beach, Sun, BBQ and crocodiles, what else did you think there was? Actually There was alot more",
        imageUrl:"https://www.dertour-reisebuero.de/wp-content/uploads/2023/05/GettyImages-1397783986-1024x683.jpg",
    },

    {
        title:"Snowy Castle in Moscow",
        location: "Russia, Moscow",
        startDate: "22. September",
        endDate:"11. November",
        description: "It was cold, but cool Castle and great beer",
        imageUrl:"https://fandrik-adventures.com/wp-content/uploads/2020/06/bunte-tuerme-basilius-kathedrale-1.jpg",
    },
    {
        title:"Paris was not that romantic",
        location: "France, Paris",
        startDate: "26. March",
        endDate:"11. April",
        description: "Movies often say, that Paris is the most romantic City, but we have differnt thoughts",
        imageUrl:"https://www.americanexpress.com/de-de/amexcited/media/cache/default/cms/2022/03/paris-sehenswuerdigkeiten-titelbild.jpg",
    },
    {
        title:"Techtravel in Tokyo",
        location: "Japan, Tokyo",
        startDate: "04. August",
        endDate:"12. August",
        description: "There were alot of amazing Tech gadgets, that i found interesting",
        imageUrl:"https://media.cntraveler.com/photos/63482b255e7943ad4006df0b/16:9/w_2560%2Cc_limit/tokyoGettyImages-1031467664.jpeg",
    },
    {
        title:"Techtravel in Tokyo",
        location: "Japan, Tokyo",
        startDate: "04. August",
        endDate:"12. August",
        description: "There were alot of amazing Tech gadgets, that i found interesting",
        imageUrl:"https://media.cntraveler.com/photos/63482b255e7943ad4006df0b/16:9/w_2560%2Cc_limit/tokyoGettyImages-1031467664.jpeg",
    },

    {
        title:"History night Berlin",
        location: "Berlin, Germany",
        startDate: "09. February",
        endDate:"31. Ferbruary",
        description: "Berlin is full of History, starting with the Berlin-Gate and continueing with the fall of the Wall",
        imageUrl:"https://a.cdn-hotels.com/gdcs/production154/d1887/471414c9-f456-4041-83f5-d7b61063d287.jpg?impolicy=fcrop&w=800&h=533&q=medium",
    },

    {
        title:"Paris was not that romantic",
        location: "France, Paris",
        startDate: "26. March",
        endDate:"11. April",
        description: "Movies often say, that Paris is the most romantic City, but we have differnt thoughts",
        imageUrl:"https://www.americanexpress.com/de-de/amexcited/media/cache/default/cms/2022/03/paris-sehenswuerdigkeiten-titelbild.jpg",
    },

    {
        title:"Sunny adventures in Florida",
        location: "US, Florida",
        startDate: "02. May",
        endDate:"12. May",
        description: "Beach, Sun, BBQ and crocodiles, what else did you think there was? Actually There was alot more",
        imageUrl:"https://www.dertour-reisebuero.de/wp-content/uploads/2023/05/GettyImages-1397783986-1024x683.jpg",
    },

    {
        title:"Snowy Castle in Moscow",
        location: "Russia, Moscow",
        startDate: "22. September",
        endDate:"11. November",
        description: "It was cold, but cool Castle and great beer",
        imageUrl:"https://fandrik-adventures.com/wp-content/uploads/2020/06/bunte-tuerme-basilius-kathedrale-1.jpg",
    },
    {
        title:"Paris was not that romantic",
        location: "France, Paris",
        startDate: "26. March",
        endDate:"11. April",
        description: "Movies often say, that Paris is the most romantic City, but we have differnt thoughts",
        imageUrl:"https://www.americanexpress.com/de-de/amexcited/media/cache/default/cms/2022/03/paris-sehenswuerdigkeiten-titelbild.jpg",
    },
    {
        title:"Techtravel in Tokyo",
        location: "Japan, Tokyo",
        startDate: "04. August",
        endDate:"12. August",
        description: "There were alot of amazing Tech gadgets, that i found interesting",
        imageUrl:"https://media.cntraveler.com/photos/63482b255e7943ad4006df0b/16:9/w_2560%2Cc_limit/tokyoGettyImages-1031467664.jpeg",
    },
    {
        title:"Techtravel in Tokyo",
        location: "Japan, Tokyo",
        startDate: "04. August",
        endDate:"12. August",
        description: "There were alot of amazing Tech gadgets, that i found interesting",
        imageUrl:"https://media.cntraveler.com/photos/63482b255e7943ad4006df0b/16:9/w_2560%2Cc_limit/tokyoGettyImages-1031467664.jpeg",
    },

    {
        title:"History night Berlin",
        location: "Berlin, Germany",
        startDate: "09. February",
        endDate:"31. Ferbruary",
        description: "Berlin is full of History, starting with the Berlin-Gate and continueing with the fall of the Wall",
        imageUrl:"https://a.cdn-hotels.com/gdcs/production154/d1887/471414c9-f456-4041-83f5-d7b61063d287.jpg?impolicy=fcrop&w=800&h=533&q=medium",
    },

    {
        title:"Paris was not that romantic",
        location: "France, Paris",
        startDate: "26. March",
        endDate:"11. April",
        description: "Movies often say, that Paris is the most romantic City, but we have differnt thoughts",
        imageUrl:"https://www.americanexpress.com/de-de/amexcited/media/cache/default/cms/2022/03/paris-sehenswuerdigkeiten-titelbild.jpg",
    },

    {
        title:"Sunny adventures in Florida",
        location: "US, Florida",
        startDate: "02. May",
        endDate:"12. May",
        description: "Beach, Sun, BBQ and crocodiles, what else did you think there was? Actually There was alot more",
        imageUrl:"https://www.dertour-reisebuero.de/wp-content/uploads/2023/05/GettyImages-1397783986-1024x683.jpg",
    },

    {
        title:"Snowy Castle in Moscow",
        location: "Russia, Moscow",
        startDate: "22. September",
        endDate:"11. November",
        description: "It was cold, but cool Castle and great beer",
        imageUrl:"https://fandrik-adventures.com/wp-content/uploads/2020/06/bunte-tuerme-basilius-kathedrale-1.jpg",
    },
    {
        title:"Paris was not that romantic",
        location: "France, Paris",
        startDate: "26. March",
        endDate:"11. April",
        description: "Movies often say, that Paris is the most romantic City, but we have differnt thoughts",
        imageUrl:"https://www.americanexpress.com/de-de/amexcited/media/cache/default/cms/2022/03/paris-sehenswuerdigkeiten-titelbild.jpg",
    },
    {
        title:"Techtravel in Tokyo",
        location: "Japan, Tokyo",
        startDate: "04. August",
        endDate:"12. August",
        description: "There were alot of amazing Tech gadgets, that i found interesting",
        imageUrl:"https://media.cntraveler.com/photos/63482b255e7943ad4006df0b/16:9/w_2560%2Cc_limit/tokyoGettyImages-1031467664.jpeg",
    },
]